from math import *

Primes = [2] # This list will contain all primes calculated

def appPrimes(n):
    global Primes
    Primes.append(n)
    
def isprime(n): # Determines if n is prime
    if n <= 1:
        return False
    elif n in Primes:
        return True
    else:
        i = 2
        while i <= sqrt(n):
            if n % i == 0:
                return False
            else:
                i += 1
        appPrimes(n)
        return True
    
def copy(l1):
    l2 = []
    for i in l1:
        l2.append(i)
    return l2
    
for i in range(3, 1001, 2): # This calculates all primes under 1000 for b
    nothing = isprime(i)

primesb = copy(Primes) # Primes will whange so I copied it

def f(n,a,b):
    return n*n+a*n+b

maxcounter = 0 # number of primes generated by the best configuration
abuffer = 0 # a of the best configuration
bbuffer = 0 # b of the best configuration

for b in primesb: # Check the configurations
    for a in range(-b-1, 1001):
        n = 1
        while isprime(f(n,a,b)):
            n += 1
        if n > maxcounter:
            maxcounter = n
            abuffer = a
            bbuffer = b

print "Answer is", abuffer*bbuffer